package com.shopl.sdg.model

import com.shopl.sdg.navigation.ComponentDestination
import kotlinx.collections.immutable.persistentListOf

internal val components = persistentListOf(
    ComponentDestination.Avatar,
    ComponentDestination.AttachmentList,
    ComponentDestination.Badge.CapsuleBadge,
    ComponentDestination.Badge.BoxBadge,
    ComponentDestination.Button.BottomButton,
    ComponentDestination.Button.BoxButton,
    ComponentDestination.Button.CapsuleButton,
    ComponentDestination.Button.FloatingButton,
    ComponentDestination.Button.GhostButton,
    ComponentDestination.Button.IconButton,
    ComponentDestination.Calendar,
    ComponentDestination.Checkbox,
    ComponentDestination.CheckOption,
    ComponentDestination.Dropdown,
    ComponentDestination.EmptyIcon.BasicEmptyIcon,
    ComponentDestination.EmptyIcon.ContentsEmptyIcon,
    ComponentDestination.Indicator.TextIndicator,
    ComponentDestination.Indicator.NumberIndicator,
    ComponentDestination.Indicator.DotIndicator,
    ComponentDestination.IconLabel,
    ComponentDestination.NumberPicker,
    ComponentDestination.Progress.SystemProgress,
    ComponentDestination.Progress.CircularProgress,
    ComponentDestination.Progress.DotProgress,
    ComponentDestination.Progress.LinearProgress,
    ComponentDestination.Radio,
    ComponentDestination.SearchBar.CapsuleSearch,
    ComponentDestination.SearchBar.BoxSearch,
    ComponentDestination.SearchBar.CategorySearch,
    ComponentDestination.Segment,
    ComponentDestination.SelectInput,
    ComponentDestination.Tab.ScrollTab,
    ComponentDestination.Tab.FixedTab,
    ComponentDestination.Tab.BoxTab,
    ComponentDestination.Tab.IconTab,
    ComponentDestination.TextInput.SimpleTextInput,
    ComponentDestination.TextInput.FixedTextInput,
    ComponentDestination.TextInput.UnderlineInput,
    ComponentDestination.TextInput.LoginInput,
    ComponentDestination.Thumbnails,
    ComponentDestination.TimePicker,
    ComponentDestination.TimeSelectInput,
    ComponentDestination.Toggle,
    ComponentDestination.Tooltip,
)