package com.shopl.sdg.ui.screen.model

import com.shopl.sdg.scene.ComponentScene
import com.shopl.sdg.scene.FoundationScene
import com.shopl.sdg.scene.TemplateScene
import kotlinx.collections.immutable.persistentListOf

internal val foundationScenes = persistentListOf(
    FoundationScene.Color,
    FoundationScene.CornerRadius,
    FoundationScene.Iconography,
    FoundationScene.Spacing,
    FoundationScene.Typograph,
)

internal val componentScenes = persistentListOf(
    ComponentScene.Avatar,
    ComponentScene.AttachmentList,
    ComponentScene.Badge.CapsuleBadge,
    ComponentScene.Badge.BoxBadge,
    ComponentScene.Button.BottomButton,
    ComponentScene.Button.BoxButton,
    ComponentScene.Button.CapsuleButton,
    ComponentScene.Button.FloatingButton,
    ComponentScene.Button.GhostButton,
    ComponentScene.Button.IconButton,
    ComponentScene.Calendar,
    ComponentScene.Checkbox,
    ComponentScene.CheckOption,
    ComponentScene.Dropdown,
    ComponentScene.EmptyIcon.BasicEmptyIcon,
    ComponentScene.EmptyIcon.ContentsEmptyIcon,
    ComponentScene.Indicator.TextIndicator,
    ComponentScene.Indicator.NumberIndicator,
    ComponentScene.Indicator.DotIndicator,
    ComponentScene.IconLabel,
    ComponentScene.NumberPicker,
    ComponentScene.Progress.SystemProgress,
    ComponentScene.Progress.CircularProgress,
    ComponentScene.Progress.DotProgress,
    ComponentScene.Progress.LinearProgress,
    ComponentScene.Radio,
    ComponentScene.SearchBar.CapsuleSearch,
    ComponentScene.SearchBar.BoxSearch,
    ComponentScene.SearchBar.CategorySearch,
    ComponentScene.Segment,
    ComponentScene.SelectInput,
    ComponentScene.Tab.ScrollTab,
    ComponentScene.Tab.FixedTab,
    ComponentScene.Tab.BoxTab,
    ComponentScene.Tab.IconTab,
    ComponentScene.TextInput.SimpleTextInput,
    ComponentScene.TextInput.FixedTextInput,
    ComponentScene.TextInput.UnderlineInput,
    ComponentScene.TextInput.LoginInput,
    ComponentScene.Thumbnails,
    ComponentScene.TimePicker,
    ComponentScene.TimeSelectInput,
    ComponentScene.Toggle,
    ComponentScene.Tooltip,
)

internal val templateScenes = persistentListOf(
    TemplateScene.CalendarAndTime,
    TemplateScene.CheckboxLabel,
    TemplateScene.CheckOptionLabel,
    TemplateScene.EmptyImg,
    TemplateScene.FilterChip.NaviFilterChip,
    TemplateScene.FilterChip.BodyFilterChip,
    TemplateScene.Form.DropdownForm,
    TemplateScene.Form.SelectForm,
    TemplateScene.Form.SimpleTextForm,
    TemplateScene.Form.FixedTextForm,
    TemplateScene.Form.TimeSelectForm,
    TemplateScene.FoundationList.UserList,
    TemplateScene.FoundationList.WorkplaceList,
    TemplateScene.FoundationList.GroupAndPositionList,
    TemplateScene.History,
    TemplateScene.HistoryMini,
    TemplateScene.ListHeader,
    TemplateScene.MultiCalendar,
    TemplateScene.MultiTimePicker,
    TemplateScene.Navigation.BasicNavi,
    TemplateScene.Navigation.CategoryNavi,
    TemplateScene.Navigation.TextNavi,
    TemplateScene.Navigation.SearchNavi,
    TemplateScene.Popup.CenterPopup,
    TemplateScene.Popup.BottomPopup,
    TemplateScene.Popup.ListPopup,
    TemplateScene.Popup.MiniListPopup,
    TemplateScene.Popup.IconPopup,
    TemplateScene.Popup.ToastPopup,
    TemplateScene.Profile.BasicProfile,
    TemplateScene.Profile.SecondProfile,
    TemplateScene.Profile.SimpleProfile,
    TemplateScene.Profile.MiniProfile,
    TemplateScene.RadioLabel,
)
