name: 아이콘 변경사항 PR

on:
  push:
    branches:
      - update/icon

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Create Pull Request Update Icon
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const branchName = context.ref.replace('refs/heads/', '');

            await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: "아이콘 업데이트",
              head: branchName,
              base: "main",
              body: "아이콘 변경사항이 있습니다."
            });