name: Maven Central 배포

#on:
#  pull_request:
#    types: [closed]
#    branches:
#      - main
on:
  push:
    branches:
      - document/scott/SH-11796-deploy-automation

jobs:
  publish:
    #    if: |
    #      github.event.pull_request.merged == true &&
    #      (
    #        contains(join(github.event.pull_request.labels.*.name, ','), 'major') ||
    #        contains(join(github.event.pull_request.labels.*.name, ','), 'minor') ||
    #        contains(join(github.event.pull_request.labels.*.name, ','), 'patch')
    #      )
    runs-on: ubuntu-latest

    steps:
      - name: Slack Notify Build Start
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_TITLE: "SDG 빌드"
          SLACK_MESSAGE: |
            :rocket: *[빌드 시작]*  
            브랜치: ${{ github.ref }}
            커밋: ${{ github.sha }}
            실행자: ${{ github.actor }}
          SLACK_COLOR: '#CCCCFF'

      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Restore secring.gpg
        run: |
          echo "${{ secrets.SIGNING_SECRET_KEY_RING_FILE }}" | base64 --decode > ./secring.gpg

      - name: Create local gradle.properties with secrets
        run: |
          echo "mavenCentralUsername=${{ secrets.MAVEN_CENTRAL_USER_NAME }}" >> ./gradle.properties
          echo "mavenCentralPassword=${{ secrets.MAVEN_CENTRAL_PASSWORD }}" >> ./gradle.properties
          echo "signing.keyId=${{ secrets.SIGNING_KEY_ID }}" >> ./gradle.properties
          echo "signing.password=${{ secrets.SIGNING_PASSWORD }}" >> ./gradle.properties
          echo "signing.secretKeyRingFile=$(pwd)/secring.gpg" >> gradle.properties

      - name: Publish to Maven Central
        working-directory: .
        run: ./gradlew publishAndReleaseToMavenCentral --no-configuration-cache

      - name: Clean up secring.gpg
        run: rm -f ./secring.gpg

      - name: Slack Notify Build Success
        if: success()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_TITLE: "SDG 빌드"
          SLACK_MESSAGE: |
            :white_check_mark: *[빌드 성공]*  
            브랜치: ${{ github.ref }}
            커밋: ${{ github.sha }}
            실행자: ${{ github.actor }}
          SLACK_COLOR: '#00C851'

      - name: Slack Notify Build Failure
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_TITLE: "SDG 빌드"
          SLACK_MESSAGE: |
            :x: *[빌드 실패]*  
            브랜치: ${{ github.ref }}
            커밋: ${{ github.sha }}
            실행자: ${{ github.actor }}
          SLACK_COLOR: '#ff4444'
