name: 아이콘 변경사항 PR

on:
  push:
    branches:
      - update/icon

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Create Pull Request Update Icon
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const branchName = context.ref.replace('refs/heads/', '');

            try {
              await github.rest.pulls.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: "아이콘 업데이트",
                head: branchName,
                base: "main",
                body: "아이콘 변경사항이 있습니다."
              });
              console.log("새 PR을 생성했습니다.");
            } catch (e) {
              if (e.status === 422 && e.message.includes("A pull request already exists")) {
                console.log("이미 PR이 존재하므로 생성 작업을 건너뜁니다.");
              } else {
                throw e;
              }
            }